# Generated by Django 6.0.5 on 2026-05-17 13:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reservation', models.DateTimeField(default=django.utils.timezone.now)),
                ('position_file', models.IntegerField(default=0)),
                ('statut', models.CharField(choices=[('active', 'Active'), ('annulee', 'Annulée'), ('expiree', 'Expirée'), ('honoree', 'Honorée')], default='active', max_length=32)),
                ('lecteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ouvrage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.ouvrage')),
            ],
            options={
                'ordering': ['date_reservation'],
            },
        ),
    ]
