# Generated by Django 6.0.5 on 2026-05-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='statut',
            field=models.CharField(
                choices=[
                    ('active', 'En attente'),
                    ('honoree', 'Confirmée'),
                    ('expiree', 'Terminée'),
                    ('annulee', 'Annulée'),
                ],
                default='active',
                max_length=32,
            ),
        ),
    ]
