# Generated by Django 6.0.5 on 2026-05-17 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ouvrage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=32, unique=True)),
                ('titre', models.CharField(max_length=300)),
                ('auteur', models.CharField(max_length=200)),
                ('sujet', models.CharField(blank=True, max_length=200)),
                ('editeur', models.CharField(blank=True, max_length=200)),
                ('annee_publication', models.IntegerField(blank=True, null=True)),
                ('resume', models.TextField(blank=True)),
                ('couverture', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Exemplaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('disponible', 'Disponible'), ('emprunte', 'Emprunte'), ('reserve', 'Reserve'), ('en_retard', 'En retard'), ('maintenance', 'Maintenance'), ('perdu', 'Perdu')], default='disponible', max_length=32)),
                ('ouvrage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exemplaires', to='catalogue.ouvrage')),
            ],
        ),
    ]
