# Generated by Django 6.0.4 on 2026-05-17 19:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_favorite'),
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_demande', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_debut_souhaite', models.DateField()),
                ('date_fin_souhaite', models.DateField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('rejete', 'Refusé'), ('annulee', 'Annulée')], default='en_attente', max_length=32)),
                ('commentaire', models.TextField(blank=True)),
                ('lecteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ouvrage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.ouvrage')),
            ],
            options={
                'ordering': ['-date_demande'],
            },
        ),
    ]
