# Generated by Django 6.0.4 on 2026-05-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_loanrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequest',
            name='date_debut_souhaite',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='date_fin_souhaite',
            field=models.DateField(blank=True, null=True),
        ),
    ]
