# Generated by Django 6.0.4 on 2026-05-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type_notification',
            field=models.CharField(choices=[('rappel', 'Rappel'), ('retard', 'Retard'), ('disponibilite', 'Disponibilité'), ('reservation', 'Demande'), ('emprunt', 'Emprunt'), ('refus', 'Refus')], max_length=32),
        ),
    ]
